method: sft
run_name: olmo3-7b-instruct-sft-standard-partition
offline: false
backend: trl
llamafactory: null

container:
  image: /scratch/project_465002530/containers/post-training-rocm7.2.4-py3.12-torch2.9.1-trl1.7.0-olmo-patched.sif 
  bind_mounts:
    - /pfs/lustrep3/scratch/project_465002530/users/krishnak/post-training/
    - /scratch/project_465002530/users/krishnak
  path: /opt/venv/bin:/opt/rocm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  env_file: env/lumi.env

model:
  name_or_path: allenai/Olmo-3-7B-Think-SFT
  attn_implementation: flash_attention_2
  dtype: bfloat16

training:
  max_steps: null
  num_train_epochs: 2.0
  num_training_samples: null
  num_training_tokens: null
  learning_rate: 8.0e-05
  effective_batch_size: 32
  per_device_train_batch_size: 1
  warmup_steps: 0.03
  lr_scheduler_type: linear
  lr_scheduler_kwargs:
    min_lr_rate: null
  adam_beta1: 0.9
  adam_beta2: 0.95
  weight_decay: 0.0
  adam_epsilon: 1.0e-08
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
    determinism_check: default
    debug: false
    early_stop: true
  bf16: true
  seed: 42
  use_liger_kernel: true

checkpointing:
  save_steps: 250
  save_total_limit: 3
  inference_checkpoint_steps: 250
  inference_checkpoint_path: inference_checkpoints

data:
  chat_template: olmo3-instruct-sft
  num_proc: 32
  datasets:
  - name: dolci-instruct-sft
    path: allenai/Dolci-Instruct-SFT
    data_dir: null
    subset: null
    split: train
    weight: 1.0
    transform: null

sft:
  max_seq_length: 32768
  packing: true
  dataset_num_proc: 32


deepspeed:
  bf16:
    enabled: true
  zero_optimization:
    stage: 2
    overlap_comm: true
    contiguous_gradients: true
    reduce_scatter: true
  gradient_clipping: 1.0
  train_micro_batch_size_per_gpu: "auto"
  gradient_accumulation_steps: "auto"
  train_batch_size: "auto"
  optimizer:
    type: AdamW
    params:
      lr: "auto"
      betas: "auto"
      eps: "auto"
      weight_decay: "auto"

accelerate:
  mixed_precision: bf16
  use_deepspeed: true
  deepspeed_multinode_launcher: standard
  same_network: true
  rdzv_backend: static
  dynamo_backend: inductor

logging:
  report_to:
  - wandb
  - tensorboard
  wandb_project: sft-training
  logging_steps: 10
  include_num_input_tokens_seen: non_padding

slurm:
  account: "project_465002530"
  partition: "standard-g"
  num_nodes: 4
  gpus_per_node: 8
  cpus_per_task: 56
  wall_time: "36:00:00"
  job_name: "sft-olmo3"
  signal_time_seconds: 300                   # SIGUSR1 sent this many seconds before timeout to trigger self-healing
  max_failures: 1                            # Self-healing retry limit
  mem: "256G"

debug:
  enabled: false
  override_existing: false

paths:
  output_base: outputs
  debug_base: outputs/debug
